recipe: default.v1
language: br
# https://rasa.com/docs/rasa/model-configuration/

# DIET PURO
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# DIET + BERTIMBAU
# pipeline:
#   - name: WhitespaceTokenizer
#   - name: LanguageModelFeaturizer
#     model_name: "bert"
#     model_weights: "neuralmind/bert-base-portuguese-cased"
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.7
#     ambiguity_threshold: 0.1

# DIET + pre train models
# pipeline:
#   - name: WhitespaceTokenizer
#   - name: LanguageModelFeaturizer
#     model_name: "gpt2"
#     # model_name: "bert"
#     # model_name: "xlnet"
#     # model_name: "distilbert"
#     # model_name: "roberta"
#     # model_name: "gpt"
#     # KeyError: "'camembert' not a valid model name. Choose from ['bert', 'gpt', 'gpt2', 'xlnet', 'distilbert', 'roberta'] or createa new class inheriting from this class to support your model."
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.7
#     ambiguity_threshold: 0.1
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
